# Generated by Django 5.2.17 on 2026-09-23 12:04

import django.db.models.deletion
import django.utils.timezone
import materials.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=60, unique=True, verbose_name="адрес (slug)"
                    ),
                ),
            ],
            options={
                "verbose_name": "тег",
                "verbose_name_plural": "теги",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="название")),
                (
                    "teacher",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="преподаватель"
                    ),
                ),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("lectures", "Конспект лекций"),
                            ("seminars", "Семинары"),
                            ("tickets", "Билеты"),
                            ("cheatsheet", "Шпаргалка"),
                            ("problems", "Задачи"),
                            ("other", "Другое"),
                        ],
                        default="lectures",
                        max_length=20,
                        verbose_name="тип",
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        blank=True,
                        help_text="Например: 2025/2026",
                        max_length=9,
                        verbose_name="учебный год",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Поддерживается Markdown и LaTeX",
                        verbose_name="описание",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=255,
                        upload_to=materials.models.material_upload_to,
                        verbose_name="файл",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="исходное имя файла"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="размер, байт"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="загружен",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменён"),
                ),
                (
                    "downloads_count",
                    models.PositiveIntegerField(default=0, verbose_name="скачиваний"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "На проверке"),
                            ("approved", "Одобрен"),
                            ("rejected", "Отклонён"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="статус",
                    ),
                ),
                (
                    "moderation_note",
                    models.TextField(
                        blank=True,
                        help_text="Виден автору, например причина отклонения",
                        verbose_name="комментарий модератора",
                    ),
                ),
                (
                    "moderated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="дата модерации"
                    ),
                ),
                (
                    "search_text",
                    models.TextField(
                        blank=True, editable=False, verbose_name="поисковый индекс"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="materials",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="автор загрузки",
                    ),
                ),
                (
                    "moderated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderated_materials",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="модератор",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="materials",
                        to="catalog.semester",
                        verbose_name="семестр",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="materials",
                        to="catalog.subject",
                        verbose_name="предмет",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="materials",
                        to="materials.tag",
                        verbose_name="теги",
                    ),
                ),
            ],
            options={
                "verbose_name": "материал",
                "verbose_name_plural": "материалы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Поддерживается Markdown и LaTeX",
                        max_length=10000,
                        verbose_name="текст",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создан"),
                ),
                (
                    "is_hidden",
                    models.BooleanField(
                        default=False, verbose_name="скрыт модератором"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="автор",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="materials.material",
                        verbose_name="материал",
                    ),
                ),
            ],
            options={
                "verbose_name": "комментарий",
                "verbose_name_plural": "комментарии",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaterialLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="materials.material",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "оценка",
                "verbose_name_plural": "оценки",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("material", "user"), name="unique_material_like"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(
                fields=["status", "-created_at"], name="materials_m_status_bac842_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(
                fields=["status", "-downloads_count"],
                name="materials_m_status_009569_idx",
            ),
        ),
    ]
