# Generated by Django 5.2.17 on 2026-09-23 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="название"
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        help_text="Например: «Мехмат»",
                        max_length=50,
                        verbose_name="краткое название",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=60, unique=True, verbose_name="адрес (slug)"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Поддерживается Markdown",
                        verbose_name="описание",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="показывать на сайте"
                    ),
                ),
            ],
            options={
                "verbose_name": "факультет",
                "verbose_name_plural": "факультеты",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="название")),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        help_text="Например: ФМиМ",
                        max_length=30,
                        verbose_name="сокращение",
                    ),
                ),
                ("slug", models.SlugField(max_length=60, verbose_name="адрес (slug)")),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="код направления"
                    ),
                ),
                (
                    "degree",
                    models.CharField(
                        choices=[
                            ("bachelor", "Бакалавриат"),
                            ("specialist", "Специалитет"),
                            ("master", "Магистратура"),
                        ],
                        default="bachelor",
                        max_length=20,
                        verbose_name="уровень",
                    ),
                ),
                (
                    "duration_years",
                    models.PositiveSmallIntegerField(
                        default=4, verbose_name="срок обучения, лет"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Поддерживается Markdown",
                        verbose_name="описание",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="показывать на сайте"
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specialties",
                        to="catalog.faculty",
                        verbose_name="факультет",
                    ),
                ),
            ],
            options={
                "verbose_name": "специальность",
                "verbose_name_plural": "специальности",
                "ordering": ["faculty", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(verbose_name="номер курса"),
                ),
                (
                    "specialty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="catalog.specialty",
                        verbose_name="специальность",
                    ),
                ),
            ],
            options={
                "verbose_name": "курс",
                "verbose_name_plural": "курсы",
                "ordering": ["specialty", "number"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="название")),
                ("slug", models.SlugField(max_length=80, verbose_name="адрес (slug)")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Поддерживается Markdown и LaTeX",
                        verbose_name="описание",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="показывать на сайте"
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="catalog.faculty",
                        verbose_name="факультет",
                    ),
                ),
            ],
            options={
                "verbose_name": "предмет",
                "verbose_name_plural": "предметы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(verbose_name="номер семестра"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semesters",
                        to="catalog.course",
                        verbose_name="курс",
                    ),
                ),
                (
                    "subjects",
                    models.ManyToManyField(
                        blank=True,
                        related_name="semesters",
                        to="catalog.subject",
                        verbose_name="предметы",
                    ),
                ),
            ],
            options={
                "verbose_name": "семестр",
                "verbose_name_plural": "семестры",
                "ordering": ["course", "number"],
            },
        ),
        migrations.AddConstraint(
            model_name="specialty",
            constraint=models.UniqueConstraint(
                fields=("faculty", "slug"), name="unique_specialty_slug_per_faculty"
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.UniqueConstraint(
                fields=("specialty", "number"), name="unique_course_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(
                fields=("faculty", "slug"), name="unique_subject_slug_per_faculty"
            ),
        ),
        migrations.AddConstraint(
            model_name="semester",
            constraint=models.UniqueConstraint(
                fields=("course", "number"), name="unique_semester_number"
            ),
        ),
    ]
